version: '3'
services:
  backend:
    build:
      context: ./school-intranet-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/school_intranet
      - LDAP_URL=ldap://172.20.50.50
      - LDAP_BIND_DN=CN=Administrateur,CN=Users,DC=home,DC=local
      - LDAP_BIND_PASSWORD=Bmw1999
      - LDAP_SEARCH_BASE=DC=home,DC=local
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
git add 